function [pyDict] = exportToPythonDict(featureStruct)
%EXPORTTOPYTHONDICT Converts a matlab struct to a python dictionary
%   Detailed explanation goes here

    pyDict = py.dict(pyargs('features',featureStruct.dataAsArray,...
        'featureNames',featureStruct.featureNames,...
        'label',featureStruct.Label',...
        'labelAsMatrix',featureStruct.labelAsMatrix,...
        'uniqueClasses',featureStruct.uniqueClasses'));

end

